# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [1]:
# Import libraries
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
pokemon = pd.read_csv('/Users/erinberardi/Erin_dataV2-labs/module-2/Two-Sample-Hypothesis-Tests/Pokemon.csv')

In [3]:
pokemon.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [5]:
pok_add = pokemon['Total']==pokemon['HP']+pokemon['Attack']+pokemon['Defense']+pokemon['Sp. Atk']+pokemon['Sp. Def']+pokemon['Speed']
pok_add
pok_add.unique()


array([ True])

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

# Creating Combo-type column

In [6]:
pokemon['Combo Type']=pokemon['Type 1'] + ('-'+pokemon['Type 2']).fillna('')
pokemon.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary    Combo Type  
0       65       65     45           1      False  Grass-Poison  
1       80       80     60           1      False  Grass-Poison  
2      100      100     80           1      False  Grass-Poison  
3      122      120     80           1      False  Grass-Poison  
4       60       50     65           1      False          Fire

# treat null values

In [7]:

pokemon['Type 2'].fillna('NA', inplace = True)
unique_type = list(pokemon['Type 2'].unique())
unique_type

['Poison',
 'NA',
 'Flying',
 'Dragon',
 'Ground',
 'Fairy',
 'Grass',
 'Fighting',
 'Psychic',
 'Steel',
 'Ice',
 'Rock',
 'Dark',
 'Water',
 'Electric',
 'Fire',
 'Ghost',
 'Bug',
 'Normal']

# Encoding the two Pokemon types.   Using OneHotEncoding 

In [8]:
from sklearn.preprocessing import OneHotEncoder
type1 = pokemon[['Type 1']]
print(type1)
encoder = OneHotEncoder().fit(type1)
encoded = encoder.transform(type1).toarray()
cols = encoder.get_feature_names()
type1_encoded = pd.DataFrame(encoded,columns=cols)
type1_encoded

      Type 1
0      Grass
1      Grass
2      Grass
3      Grass
4       Fire
..       ...
795     Rock
796     Rock
797  Psychic
798  Psychic
799     Fire

[800 rows x 1 columns]


x0_Bug  x0_Dark  x0_Dragon  x0_Electric  x0_Fairy  x0_Fighting  x0_Fire  \
0       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
1       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
2       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
3       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
4       0.0      0.0        0.0          0.0       0.0          0.0      1.0   
..      ...      ...        ...          ...       ...          ...      ...   
795     0.0      0.0        0.0          0.0       0.0          0.0      0.0   
796     0.0      0.0        0.0          0.0       0.0          0.0      0.0   
797     0.0      0.0        0.0          0.0       0.0          0.0      0.0   
798     0.0      0.0        0.0          0.0       0.0          0.0      0.0   
799     0.0      0.0        0.0          0.0       0.0          0.0      1.0   

     x0_Flying  x0_Ghost  x0_Grass  x0_Ground  x0_Ice  x0_Normal  x0_Poison  \
0          0.0       0.0       1.0        0.0     0.0        0.0        0.0   
1          0.0       0.0       1.0        0.0     0.0        0.0        0.0   
2          0.0       0.0       1.0        0.0     0.0        0.0        0.0   
3          0.0       0.0       1.0        0.0     0.0        0.0        0.0   
4          0.0       0.0       0.0        0.0     0.0        0.0        0.0   
..         ...       ...       ...        ...     ...        ...        ...   
795        0.0       0.0       0.0        0.0     0.0        0.0        0.0   
796        0.0       0.0       0.0        0.0     0.0        0.0        0.0   
797        0.0       0.0       0.0        0.0     0.0        0.0        0.0   
798        0.0       0.0       0.0        0.0     0.0        0.0        0.0   
799        0.0       0.0       0.0        0.0     0.0        0.0        0.0   

     x0_Psychic  x0_Rock  x0_Steel  x0_Water  
0           0.0      0.0       0.0       0.0  
1           0.0      0.0       0.0       0.0  
2           0.0      0.0       0.0       0.0  
3           0.0      0.0       0.0       0.0  
4           0.0      0.0       0.0       0.0  
..          ...      ...       ...       ...  
795         0.0      1.0       0.0       0.0  
796         0.0      1.0       0.0       0.0  
797         1.0      0.0       0.0       0.0  
798         1.0      0.0       0.0       0.0  
799         0.0      0.0       0.0       0.0  

[800 rows x 18 columns]

In [9]:
type2 = pokemon[['Type 2']]
encoder = OneHotEncoder().fit(type2)
encoded = encoder.transform(type2).toarray()
cols2 = encoder.get_feature_names()
type2_encoded = pd.DataFrame(encoded,columns=cols2)
type2_encoded = type2_encoded.drop(['x0_NA'], axis=1)
type2_encoded

x0_Bug  x0_Dark  x0_Dragon  x0_Electric  x0_Fairy  x0_Fighting  x0_Fire  \
0       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
1       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
2       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
3       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
4       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
..      ...      ...        ...          ...       ...          ...      ...   
795     0.0      0.0        0.0          0.0       1.0          0.0      0.0   
796     0.0      0.0        0.0          0.0       1.0          0.0      0.0   
797     0.0      0.0        0.0          0.0       0.0          0.0      0.0   
798     0.0      1.0        0.0          0.0       0.0          0.0      0.0   
799     0.0      0.0        0.0          0.0       0.0          0.0      0.0   

     x0_Flying  x0_Ghost  x0_Grass  x0_Ground  x0_Ice  x0_Normal  x0_Poison  \
0          0.0       0.0       0.0        0.0     0.0        0.0        1.0   
1          0.0       0.0       0.0        0.0     0.0        0.0        1.0   
2          0.0       0.0       0.0        0.0     0.0        0.0        1.0   
3          0.0       0.0       0.0        0.0     0.0        0.0        1.0   
4          0.0       0.0       0.0        0.0     0.0        0.0        0.0   
..         ...       ...       ...        ...     ...        ...        ...   
795        0.0       0.0       0.0        0.0     0.0        0.0        0.0   
796        0.0       0.0       0.0        0.0     0.0        0.0        0.0   
797        0.0       1.0       0.0        0.0     0.0        0.0        0.0   
798        0.0       0.0       0.0        0.0     0.0        0.0        0.0   
799        0.0       0.0       0.0        0.0     0.0        0.0        0.0   

     x0_Psychic  x0_Rock  x0_Steel  x0_Water  
0           0.0      0.0       0.0       0.0  
1           0.0      0.0       0.0       0.0  
2           0.0      0.0       0.0       0.0  
3           0.0      0.0       0.0       0.0  
4           0.0      0.0       0.0       0.0  
..          ...      ...       ...       ...  
795         0.0      0.0       0.0       0.0  
796         0.0      0.0       0.0       0.0  
797         0.0      0.0       0.0       0.0  
798         0.0      0.0       0.0       0.0  
799         0.0      0.0       0.0       1.0  

[800 rows x 18 columns]

In [10]:
poke_encode= type1_encoded+type2_encoded
poke_encode

x0_Bug  x0_Dark  x0_Dragon  x0_Electric  x0_Fairy  x0_Fighting  x0_Fire  \
0       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
1       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
2       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
3       0.0      0.0        0.0          0.0       0.0          0.0      0.0   
4       0.0      0.0        0.0          0.0       0.0          0.0      1.0   
..      ...      ...        ...          ...       ...          ...      ...   
795     0.0      0.0        0.0          0.0       1.0          0.0      0.0   
796     0.0      0.0        0.0          0.0       1.0          0.0      0.0   
797     0.0      0.0        0.0          0.0       0.0          0.0      0.0   
798     0.0      1.0        0.0          0.0       0.0          0.0      0.0   
799     0.0      0.0        0.0          0.0       0.0          0.0      1.0   

     x0_Flying  x0_Ghost  x0_Grass  x0_Ground  x0_Ice  x0_Normal  x0_Poison  \
0          0.0       0.0       1.0        0.0     0.0        0.0        1.0   
1          0.0       0.0       1.0        0.0     0.0        0.0        1.0   
2          0.0       0.0       1.0        0.0     0.0        0.0        1.0   
3          0.0       0.0       1.0        0.0     0.0        0.0        1.0   
4          0.0       0.0       0.0        0.0     0.0        0.0        0.0   
..         ...       ...       ...        ...     ...        ...        ...   
795        0.0       0.0       0.0        0.0     0.0        0.0        0.0   
796        0.0       0.0       0.0        0.0     0.0        0.0        0.0   
797        0.0       1.0       0.0        0.0     0.0        0.0        0.0   
798        0.0       0.0       0.0        0.0     0.0        0.0        0.0   
799        0.0       0.0       0.0        0.0     0.0        0.0        0.0   

     x0_Psychic  x0_Rock  x0_Steel  x0_Water  
0           0.0      0.0       0.0       0.0  
1           0.0      0.0       0.0       0.0  
2           0.0      0.0       0.0       0.0  
3           0.0      0.0       0.0       0.0  
4           0.0      0.0       0.0       0.0  
..          ...      ...       ...       ...  
795         0.0      1.0       0.0       0.0  
796         0.0      1.0       0.0       0.0  
797         1.0      0.0       0.0       0.0  
798         1.0      0.0       0.0       0.0  
799         0.0      0.0       0.0       1.0  

[800 rows x 18 columns]

# Encoding Pokemon Type1 & Type2 -- Bullying into Submission

# Create columns for Pokemon types.  Fill all with 0.

In [11]:

pokemon1 = pokemon.reindex(pokemon.columns.tolist() + unique_type, axis=1, fill_value=0)

pokemon1

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire      NA    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  ...  Steel  Ice  Rock Dark  Water  Electric  Fire  \
0         65       65  ...      0    0     0    0      0         0     0   
1         80       80  ...      0    0     0    0      0         0     0   
2        100      100  ...      0    0     0    0      0         0     0   
3        122      120  ...      0    0     0    0      0         0     0   
4         60       50  ...      0    0     0    0      0         0     0   
..       ...      ...  ...    ...  ...   ...  ...    ...       ...   ...   
795      100      150  ...      0    0     0    0      0         0     0   
796      160      110  ...      0    0     0    0      0         0     0   
797      150      130  ...      0    0     0    0      0         0     0   
798      170      130  ...      0    0     0    0      0         0     0   
799      130       90  ...      0    0     0    0      0         0     0   

     Ghost  Bug  Normal  
0        0    0       0  
1        0    0       0  
2        0    0       0  
3        0    0       0  
4        0    0       0  
..     ...  ...     ...  
795      0    0       0  
796      0    0       0  
797      0    0       0  
798      0    0       0  
799      0    0       0  

[800 rows x 33 columns]

# Check all types are there

In [12]:
pokemon1.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Combo Type',
       'Poison', 'NA', 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'],
      dtype='object')

In [13]:
pokemon1['Combo Type']

0       Grass-Poison
1       Grass-Poison
2       Grass-Poison
3       Grass-Poison
4               Fire
           ...      
795       Rock-Fairy
796       Rock-Fairy
797    Psychic-Ghost
798     Psychic-Dark
799       Fire-Water
Name: Combo Type, Length: 800, dtype: object

In [14]:
pokemon1['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [15]:
pokemon1['Type 2'].unique()

array(['Poison', 'NA', 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)

In [16]:
pokemon1['Type 1'][0]

'Grass'

In [17]:
pokemon1['Type 2'][0]

'Poison'

# Begin to create function to label all types

In [18]:
pokemon1.loc[pokemon1['Type 1'] == 'Grass','Grass'] = 1
pokemon1.loc[pokemon1['Type 2'] == 'Grass','Grass'] = 1
display(pokemon1['Grass'])


0      1
1      1
2      1
3      1
4      0
      ..
795    0
796    0
797    0
798    0
799    0
Name: Grass, Length: 800, dtype: int64

In [19]:
pokemon1['Grass'].value_counts()

0    705
1     95
Name: Grass, dtype: int64

# Function to label types 

In [20]:
def dummy_types(df):
    for type1 in df['Type 1']:
        df.loc[df['Type 1'] == type1,str(type1)] = 1
    for type2 in df['Type 2']:
        df.loc[df['Type 2'] == type2,str(type2)] = 1
    return 


In [21]:
dummy_types(pokemon1)

In [22]:
pokemon1

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire      NA    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  ...  Steel  Ice  Rock Dark  Water  Electric  Fire  \
0         65       65  ...      0    0     0    0      0         0     0   
1         80       80  ...      0    0     0    0      0         0     0   
2        100      100  ...      0    0     0    0      0         0     0   
3        122      120  ...      0    0     0    0      0         0     0   
4         60       50  ...      0    0     0    0      0         0     1   
..       ...      ...  ...    ...  ...   ...  ...    ...       ...   ...   
795      100      150  ...      0    0     1    0      0         0     0   
796      160      110  ...      0    0     1    0      0         0     0   
797      150      130  ...      0    0     0    0      0         0     0   
798      170      130  ...      0    0     0    1      0         0     0   
799      130       90  ...      0    0     0    0      1         0     1   

     Ghost  Bug  Normal  
0        0    0       0  
1        0    0       0  
2        0    0       0  
3        0    0       0  
4        0    0       0  
..     ...  ...     ...  
795      0    0       0  
796      0    0       0  
797      1    0       0  
798      0    0       0  
799      0    0       0  

[800 rows x 33 columns]

# Checking to make sure it worked

In [23]:
pokemon1['Fire'].value_counts()


0    736
1     64
Name: Fire, dtype: int64

In [24]:
pokemon1['NA'].value_counts()

0    414
1    386
Name: NA, dtype: int64

# dropping NA column

In [25]:

pokemon2 = pokemon1.drop('NA',axis = 1)

In [26]:
pokemon2.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Combo Type',
       'Poison', 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass', 'Fighting',
       'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water', 'Electric', 'Fire',
       'Ghost', 'Bug', 'Normal'],
      dtype='object')

# Dropping unnecessary columns

In [27]:
pokemon3 = pokemon2.drop(['Type 1','Type 2','#','Combo Type','Generation','Legendary','HP','Attack','Defense','Sp. Atk','Sp. Def','Speed'],axis = 1)
pokemon3.head()

Name  Total  Poison  Flying  Dragon  Ground  Fairy  Grass  \
0              Bulbasaur    318       1       0       0       0      0      1   
1                Ivysaur    405       1       0       0       0      0      1   
2               Venusaur    525       1       0       0       0      0      1   
3  VenusaurMega Venusaur    625       1       0       0       0      0      1   
4             Charmander    309       0       0       0       0      0      0   

   Fighting  Psychic  Steel  Ice  Rock  Dark  Water  Electric  Fire  Ghost  \
0         0        0      0    0     0     0      0         0     0      0   
1         0        0      0    0     0     0      0         0     0      0   
2         0        0      0    0     0     0      0         0     0      0   
3         0        0      0    0     0     0      0         0     0      0   
4         0        0      0    0     0     0      0         0     1      0   

   Bug  Normal  
0    0       0  
1    0       0  
2    0       0  
3    0       0  
4    0       0

In [28]:
pokemon = pd.read_csv('/Users/erinberardi/Erin_dataV2-labs/module-2/Two-Sample-Hypothesis-Tests/Pokemon.csv')

## Using get_dummies

In [29]:
pokemon_encode = pd.get_dummies(pokemon["Type 1"]) + pd.get_dummies(pokemon["Type 2"])
#pokemon_encode = pokemon_encode.drop('NA', axis=1)
pokemon_encode

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0      0     0       0         0      0         0     0       0      0      1   
1      0     0       0         0      0         0     0       0      0      1   
2      0     0       0         0      0         0     0       0      0      1   
3      0     0       0         0      0         0     0       0      0      1   
4      0     0       0         0      0         0     1       0      0      0   
..   ...   ...     ...       ...    ...       ...   ...     ...    ...    ...   
795    0     0       0         0      1         0     0       0      0      0   
796    0     0       0         0      1         0     0       0      0      0   
797    0     0       0         0      0         0     0       0      1      0   
798    0     1       0         0      0         0     0       0      0      0   
799    0     0       0         0      0         0     1       0      0      0   

     Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0         0    0       0       1        0     0      0      0  
1         0    0       0       1        0     0      0      0  
2         0    0       0       1        0     0      0      0  
3         0    0       0       1        0     0      0      0  
4         0    0       0       0        0     0      0      0  
..      ...  ...     ...     ...      ...   ...    ...    ...  
795       0    0       0       0        0     1      0      0  
796       0    0       0       0        0     1      0      0  
797       0    0       0       0        1     0      0      0  
798       0    0       0       0        1     0      0      0  
799       0    0       0       0        0     0      0      1  

[800 rows x 18 columns]

# *_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*

In [30]:
pokemon = pd.read_csv('/Users/erinberardi/Erin_dataV2-labs/module-2/Two-Sample-Hypothesis-Tests/Pokemon.csv')

# Trying to get one-hot-encoder

In [31]:
ohe = OneHotEncoder()
feature_arr = ohe.fit_transform(pokemon[['Type 1']]).toarray()
print(feature_arr)
feature_labels = ohe.get_feature_names()
feature_labels

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


array(['x0_Bug', 'x0_Dark', 'x0_Dragon', 'x0_Electric', 'x0_Fairy',
       'x0_Fighting', 'x0_Fire', 'x0_Flying', 'x0_Ghost', 'x0_Grass',
       'x0_Ground', 'x0_Ice', 'x0_Normal', 'x0_Poison', 'x0_Psychic',
       'x0_Rock', 'x0_Steel', 'x0_Water'], dtype=object)

In [32]:
ohe1 = OneHotEncoder()
feature_arr1 = ohe1.fit_transform(pokemon[['Type 2']]).toarray()
print(feature_arr1)
feature_labels1 = ohe1.get_feature_names()
feature_labels1

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


array(['x0_Bug', 'x0_Dark', 'x0_Dragon', 'x0_Electric', 'x0_Fairy',
       'x0_Fighting', 'x0_Fire', 'x0_Flying', 'x0_Ghost', 'x0_Grass',
       'x0_Ground', 'x0_Ice', 'x0_Normal', 'x0_Poison', 'x0_Psychic',
       'x0_Rock', 'x0_Steel', 'x0_Water', 'x0_nan'], dtype=object)

In [ ]:
#Rename columns and drop NA column

In [33]:
features = pd.DataFrame(feature_arr,columns=feature_labels)
features.columns = features.columns.str.split('_').str[1]
features

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
1    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
2    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
3    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
4    0.0   0.0     0.0       0.0    0.0       0.0   1.0     0.0    0.0    0.0   
..   ...   ...     ...       ...    ...       ...   ...     ...    ...    ...   
795  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
796  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
797  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
798  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
799  0.0   0.0     0.0       0.0    0.0       0.0   1.0     0.0    0.0    0.0   

     Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
1       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
2       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
3       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
4       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
..      ...  ...     ...     ...      ...   ...    ...    ...  
795     0.0  0.0     0.0     0.0      0.0   1.0    0.0    0.0  
796     0.0  0.0     0.0     0.0      0.0   1.0    0.0    0.0  
797     0.0  0.0     0.0     0.0      1.0   0.0    0.0    0.0  
798     0.0  0.0     0.0     0.0      1.0   0.0    0.0    0.0  
799     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  

[800 rows x 18 columns]

## Trying with all in same cell

In [36]:
X1=pokemon['Type 1']
X2=pokemon['Type 2']

encoder1 = OneHotEncoder().fit(X1)
encoder2 = OneHotEncoder().fit(X2)


encoded1 = encoder1.transform(X1).toarray()
encoded2 = encoder2.transform(X2).toarray()

cols1=encoder1.get_feature_names()
cols2=encoder2.get_feature_names()

encoded1=pd.DataFrame(encoded1, columns = cols1)
encoded2=pd.DataFrame(encoded2, columns = cols2)

ValueError: Expected 2D array, got 1D array instead:
array=['Grass' 'Grass' 'Grass' 'Grass' 'Fire' 'Fire' 'Fire' 'Fire' 'Fire'
 'Water' 'Water' 'Water' 'Water' 'Bug' 'Bug' 'Bug' 'Bug' 'Bug' 'Bug' 'Bug'
 'Normal' 'Normal' 'Normal' 'Normal' 'Normal' 'Normal' 'Normal' 'Normal'
 'Poison' 'Poison' 'Electric' 'Electric' 'Ground' 'Ground' 'Poison'
 'Poison' 'Poison' 'Poison' 'Poison' 'Poison' 'Fairy' 'Fairy' 'Fire'
 'Fire' 'Normal' 'Normal' 'Poison' 'Poison' 'Grass' 'Grass' 'Grass' 'Bug'
 'Bug' 'Bug' 'Bug' 'Ground' 'Ground' 'Normal' 'Normal' 'Water' 'Water'
 'Fighting' 'Fighting' 'Fire' 'Fire' 'Water' 'Water' 'Water' 'Psychic'
 'Psychic' 'Psychic' 'Psychic' 'Fighting' 'Fighting' 'Fighting' 'Grass'
 'Grass' 'Grass' 'Water' 'Water' 'Rock' 'Rock' 'Rock' 'Fire' 'Fire'
 'Water' 'Water' 'Water' 'Electric' 'Electric' 'Normal' 'Normal' 'Normal'
 'Water' 'Water' 'Poison' 'Poison' 'Water' 'Water' 'Ghost' 'Ghost' 'Ghost'
 'Ghost' 'Rock' 'Psychic' 'Psychic' 'Water' 'Water' 'Electric' 'Electric'
 'Grass' 'Grass' 'Ground' 'Ground' 'Fighting' 'Fighting' 'Normal' 'Poison'
 'Poison' 'Ground' 'Ground' 'Normal' 'Grass' 'Normal' 'Normal' 'Water'
 'Water' 'Water' 'Water' 'Water' 'Water' 'Psychic' 'Bug' 'Ice' 'Electric'
 'Fire' 'Bug' 'Bug' 'Normal' 'Water' 'Water' 'Water' 'Water' 'Normal'
 'Normal' 'Water' 'Electric' 'Fire' 'Normal' 'Rock' 'Rock' 'Rock' 'Rock'
 'Rock' 'Rock' 'Normal' 'Ice' 'Electric' 'Fire' 'Dragon' 'Dragon' 'Dragon'
 'Psychic' 'Psychic' 'Psychic' 'Psychic' 'Grass' 'Grass' 'Grass' 'Fire'
 'Fire' 'Fire' 'Water' 'Water' 'Water' 'Normal' 'Normal' 'Normal' 'Normal'
 'Bug' 'Bug' 'Bug' 'Bug' 'Poison' 'Water' 'Water' 'Electric' 'Fairy'
 'Normal' 'Fairy' 'Fairy' 'Psychic' 'Psychic' 'Electric' 'Electric'
 'Electric' 'Electric' 'Grass' 'Water' 'Water' 'Rock' 'Water' 'Grass'
 'Grass' 'Grass' 'Normal' 'Grass' 'Grass' 'Bug' 'Water' 'Water' 'Psychic'
 'Dark' 'Dark' 'Water' 'Ghost' 'Psychic' 'Psychic' 'Normal' 'Bug' 'Bug'
 'Normal' 'Ground' 'Steel' 'Steel' 'Fairy' 'Fairy' 'Water' 'Bug' 'Bug'
 'Bug' 'Bug' 'Bug' 'Dark' 'Normal' 'Normal' 'Fire' 'Fire' 'Ice' 'Ice'
 'Water' 'Water' 'Water' 'Ice' 'Water' 'Steel' 'Dark' 'Dark' 'Dark'
 'Water' 'Ground' 'Ground' 'Normal' 'Normal' 'Normal' 'Fighting'
 'Fighting' 'Ice' 'Electric' 'Fire' 'Normal' 'Normal' 'Electric' 'Fire'
 'Water' 'Rock' 'Rock' 'Rock' 'Rock' 'Psychic' 'Fire' 'Psychic' 'Grass'
 'Grass' 'Grass' 'Grass' 'Fire' 'Fire' 'Fire' 'Fire' 'Water' 'Water'
 'Water' 'Water' 'Dark' 'Dark' 'Normal' 'Normal' 'Bug' 'Bug' 'Bug' 'Bug'
 'Bug' 'Water' 'Water' 'Water' 'Grass' 'Grass' 'Grass' 'Normal' 'Normal'
 'Water' 'Water' 'Psychic' 'Psychic' 'Psychic' 'Psychic' 'Bug' 'Bug'
 'Grass' 'Grass' 'Normal' 'Normal' 'Normal' 'Bug' 'Bug' 'Bug' 'Normal'
 'Normal' 'Normal' 'Fighting' 'Fighting' 'Normal' 'Rock' 'Normal' 'Normal'
 'Dark' 'Dark' 'Steel' 'Steel' 'Steel' 'Steel' 'Steel' 'Steel' 'Fighting'
 'Fighting' 'Fighting' 'Electric' 'Electric' 'Electric' 'Electric'
 'Electric' 'Bug' 'Bug' 'Grass' 'Poison' 'Poison' 'Water' 'Water' 'Water'
 'Water' 'Water' 'Fire' 'Fire' 'Fire' 'Fire' 'Psychic' 'Psychic' 'Normal'
 'Ground' 'Ground' 'Ground' 'Grass' 'Grass' 'Normal' 'Dragon' 'Dragon'
 'Normal' 'Poison' 'Rock' 'Rock' 'Water' 'Water' 'Water' 'Water' 'Ground'
 'Ground' 'Rock' 'Rock' 'Rock' 'Rock' 'Water' 'Water' 'Normal' 'Normal'
 'Ghost' 'Ghost' 'Ghost' 'Ghost' 'Ghost' 'Grass' 'Psychic' 'Dark' 'Dark'
 'Psychic' 'Ice' 'Ice' 'Ice' 'Ice' 'Ice' 'Ice' 'Water' 'Water' 'Water'
 'Water' 'Water' 'Dragon' 'Dragon' 'Dragon' 'Dragon' 'Steel' 'Steel'
 'Steel' 'Steel' 'Rock' 'Ice' 'Steel' 'Dragon' 'Dragon' 'Dragon' 'Dragon'
 'Water' 'Water' 'Ground' 'Ground' 'Dragon' 'Dragon' 'Steel' 'Psychic'
 'Psychic' 'Psychic' 'Psychic' 'Grass' 'Grass' 'Grass' 'Fire' 'Fire'
 'Fire' 'Water' 'Water' 'Water' 'Normal' 'Normal' 'Normal' 'Normal'
 'Normal' 'Bug' 'Bug' 'Electric' 'Electric' 'Electric' 'Grass' 'Grass'
 'Rock' 'Rock' 'Rock' 'Rock' 'Bug' 'Bug' 'Bug' 'Bug' 'Bug' 'Bug' 'Bug'
 'Electric' 'Water' 'Water' 'Grass' 'Grass' 'Water' 'Water' 'Normal'
 'Ghost' 'Ghost' 'Normal' 'Normal' 'Normal' 'Ghost' 'Dark' 'Normal'
 'Normal' 'Psychic' 'Poison' 'Poison' 'Steel' 'Steel' 'Rock' 'Psychic'
 'Normal' 'Normal' 'Ghost' 'Dragon' 'Dragon' 'Dragon' 'Dragon' 'Normal'
 'Fighting' 'Fighting' 'Fighting' 'Ground' 'Ground' 'Poison' 'Poison'
 'Poison' 'Poison' 'Grass' 'Water' 'Water' 'Water' 'Grass' 'Grass' 'Grass'
 'Dark' 'Electric' 'Normal' 'Ground' 'Grass' 'Electric' 'Fire' 'Fairy'
 'Bug' 'Grass' 'Ice' 'Ground' 'Ice' 'Normal' 'Psychic' 'Psychic' 'Rock'
 'Ghost' 'Ice' 'Electric' 'Electric' 'Electric' 'Electric' 'Electric'
 'Electric' 'Psychic' 'Psychic' 'Psychic' 'Steel' 'Water' 'Fire' 'Normal'
 'Ghost' 'Ghost' 'Psychic' 'Water' 'Water' 'Dark' 'Grass' 'Grass' 'Normal'
 'Psychic' 'Grass' 'Grass' 'Grass' 'Fire' 'Fire' 'Fire' 'Water' 'Water'
 'Water' 'Normal' 'Normal' 'Normal' 'Normal' 'Normal' 'Dark' 'Dark'
 'Grass' 'Grass' 'Fire' 'Fire' 'Water' 'Water' 'Psychic' 'Psychic'
 'Normal' 'Normal' 'Normal' 'Electric' 'Electric' 'Rock' 'Rock' 'Rock'
 'Psychic' 'Psychic' 'Ground' 'Ground' 'Normal' 'Normal' 'Fighting'
 'Fighting' 'Fighting' 'Water' 'Water' 'Water' 'Fighting' 'Fighting' 'Bug'
 'Bug' 'Bug' 'Bug' 'Bug' 'Bug' 'Grass' 'Grass' 'Grass' 'Grass' 'Water'
 'Ground' 'Ground' 'Ground' 'Fire' 'Fire' 'Fire' 'Grass' 'Bug' 'Bug'
 'Dark' 'Dark' 'Psychic' 'Ghost' 'Ghost' 'Water' 'Water' 'Rock' 'Rock'
 'Poison' 'Poison' 'Dark' 'Dark' 'Normal' 'Normal' 'Psychic' 'Psychic'
 'Psychic' 'Psychic' 'Psychic' 'Psychic' 'Water' 'Water' 'Ice' 'Ice' 'Ice'
 'Normal' 'Normal' 'Electric' 'Bug' 'Bug' 'Grass' 'Grass' 'Water' 'Water'
 'Water' 'Bug' 'Bug' 'Grass' 'Grass' 'Steel' 'Steel' 'Steel' 'Electric'
 'Electric' 'Electric' 'Psychic' 'Psychic' 'Ghost' 'Ghost' 'Ghost'
 'Dragon' 'Dragon' 'Dragon' 'Ice' 'Ice' 'Ice' 'Bug' 'Bug' 'Ground'
 'Fighting' 'Fighting' 'Dragon' 'Ground' 'Ground' 'Dark' 'Dark' 'Normal'
 'Normal' 'Normal' 'Dark' 'Dark' 'Fire' 'Bug' 'Dark' 'Dark' 'Dark' 'Bug'
 'Bug' 'Steel' 'Rock' 'Grass' 'Flying' 'Flying' 'Electric' 'Electric'
 'Dragon' 'Dragon' 'Ground' 'Ground' 'Dragon' 'Dragon' 'Dragon' 'Water'
 'Water' 'Normal' 'Normal' 'Bug' 'Grass' 'Grass' 'Grass' 'Fire' 'Fire'
 'Fire' 'Water' 'Water' 'Water' 'Normal' 'Normal' 'Normal' 'Fire' 'Fire'
 'Bug' 'Bug' 'Bug' 'Fire' 'Fire' 'Fairy' 'Fairy' 'Fairy' 'Grass' 'Grass'
 'Fighting' 'Fighting' 'Normal' 'Psychic' 'Psychic' 'Psychic' 'Steel'
 'Steel' 'Steel' 'Steel' 'Fairy' 'Fairy' 'Fairy' 'Fairy' 'Dark' 'Dark'
 'Rock' 'Rock' 'Poison' 'Poison' 'Water' 'Water' 'Electric' 'Electric'
 'Rock' 'Rock' 'Rock' 'Rock' 'Fairy' 'Fighting' 'Electric' 'Rock' 'Dragon'
 'Dragon' 'Dragon' 'Steel' 'Ghost' 'Ghost' 'Ghost' 'Ghost' 'Ghost' 'Ghost'
 'Ghost' 'Ghost' 'Ghost' 'Ghost' 'Ice' 'Ice' 'Flying' 'Flying' 'Fairy'
 'Dark' 'Dragon' 'Rock' 'Rock' 'Psychic' 'Psychic' 'Fire'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [34]:
features1 = pd.DataFrame(feature_arr1,columns=feature_labels1)
features1.columns = features1.columns.str.split('_').str[1]
features1.drop(columns = 'nan', axis = 1, inplace = True)
features1


Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
1    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
2    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
3    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
4    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
..   ...   ...     ...       ...    ...       ...   ...     ...    ...    ...   
795  0.0   0.0     0.0       0.0    1.0       0.0   0.0     0.0    0.0    0.0   
796  0.0   0.0     0.0       0.0    1.0       0.0   0.0     0.0    0.0    0.0   
797  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    1.0    0.0   
798  0.0   1.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
799  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   

     Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
1       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
2       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
3       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
4       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
..      ...  ...     ...     ...      ...   ...    ...    ...  
795     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
796     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
797     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
798     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
799     0.0  0.0     0.0     0.0      0.0   0.0    0.0    1.0  

[800 rows x 18 columns]

In [35]:
one_hot_encoded = features + features1
one_hot_encoded

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
1    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
2    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
3    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
4    0.0   0.0     0.0       0.0    0.0       0.0   1.0     0.0    0.0    0.0   
..   ...   ...     ...       ...    ...       ...   ...     ...    ...    ...   
795  0.0   0.0     0.0       0.0    1.0       0.0   0.0     0.0    0.0    0.0   
796  0.0   0.0     0.0       0.0    1.0       0.0   0.0     0.0    0.0    0.0   
797  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    1.0    0.0   
798  0.0   1.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
799  0.0   0.0     0.0       0.0    0.0       0.0   1.0     0.0    0.0    0.0   

     Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
1       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
2       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
3       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
4       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
..      ...  ...     ...     ...      ...   ...    ...    ...  
795     0.0  0.0     0.0     0.0      0.0   1.0    0.0    0.0  
796     0.0  0.0     0.0     0.0      0.0   1.0    0.0    0.0  
797     0.0  0.0     0.0     0.0      1.0   0.0    0.0    0.0  
798     0.0  0.0     0.0     0.0      1.0   0.0    0.0    0.0  
799     0.0  0.0     0.0     0.0      0.0   0.0    0.0    1.0  

[800 rows x 18 columns]

# *_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [37]:
# your code here
corr = pokemon3.corr()
corr
#Dragon , Psychic
pokemon_best = corr.sort_values(by = 'Total', ascending=False)

pokemon_best['Total']


Total       1.000000
Dragon      0.229705
Psychic     0.124688
Steel       0.109703
Fire        0.078726
Fighting    0.077786
Ice         0.060248
Flying      0.059383
Dark        0.056154
Rock        0.032731
Electric    0.020971
Ground      0.015060
Ghost       0.003641
Water      -0.021665
Fairy      -0.036698
Grass      -0.052592
Poison     -0.090441
Normal     -0.105331
Bug        -0.145781
Name: Total, dtype: float64

# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

### Dragon or Psychic

In [38]:
grouped_max = pokemon2.groupby(['Type 1','Type 2']).agg({'Total':'max'})
grouped_max.reset_index()


Type 1    Type 2  Total
0      Bug  Electric    472
1      Bug  Fighting    600
2      Bug      Fire    550
3      Bug    Flying    600
4      Bug     Ghost    236
..     ...       ...    ...
149  Water        NA    770
150  Water    Poison    515
151  Water   Psychic    590
152  Water      Rock    495
153  Water     Steel    530

[154 rows x 3 columns]

In [39]:
best2_pokemon=grouped_max.sort_values(by=['Total'], ascending=False)
best2_pokemon.head()

Total
Type 1  Type 2         
Psychic NA          780
Dragon  Flying      780
Psychic Fighting    780
Ground  Fire        770
Water   NA          770

## Best Choice

### I would pick Dragon with Flying. (Mega Rayquaza)   Everyone knows that a flying dragon is awesome!

![MegaRayquaza.png](https://cdn.staticneo.com/w/pokemon/4/44/Megarayquaza.png)

In [40]:
pokemon[((pokemon['Type 1'] == 'Psychic') & (pokemon['Total']== 780)) |
        ((pokemon['Type 1'] == 'Dragon') & (pokemon['Total']== 780))] 

#                   Name   Type 1    Type 2  Total   HP  Attack  \
163  150    MewtwoMega Mewtwo X  Psychic  Fighting    780  106     190   
164  150    MewtwoMega Mewtwo Y  Psychic       NaN    780  106     150   
426  384  RayquazaMega Rayquaza   Dragon    Flying    780  105     180   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
163      100      154      100    130           1       True  
164       70      194      120    140           1       True  
426      100      180      100    115           3       True

In [47]:
pokemon[(pokemon['Type 1']=='Dragon') & (pokemon['Type 2']=='Flying')] #& (pokemon['Total']== 780)]

#                     Name  Type 1  Type 2  Total   HP  Attack  \
161  149                Dragonite  Dragon  Flying    600   91     134   
365  334                  Altaria  Dragon  Flying    490   75      70   
408  373                Salamence  Dragon  Flying    600   95     135   
409  373  SalamenceMega Salamence  Dragon  Flying    700   95     145   
425  384                 Rayquaza  Dragon  Flying    680  105     150   
426  384    RayquazaMega Rayquaza  Dragon  Flying    780  105     180   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
161       95      100      100     80           1      False  
365       90       70      105     80           3      False  
408       80      110       80    100           3      False  
409      130      120       90    120           3      False  
425       90      150       90     95           3       True  
426      100      180      100    115           3       True

# There was much discussion about if you have to pick a specific Pokemon or you can only pick the Type

In [48]:
# Group pokemon by type 1 and type 2 and check which combo has the highest total mean

grouped_pokemon = pokemon.groupby(['Type 1', 'Type 2']).median() #or mean
grouped_pokemon.sort_values(by = 'Total', ascending= False)

#  Total     HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1  Type 2                                                                  
Ground  Fire    383.0  770.0  100.0   180.0    160.0    150.0     90.0   90.0   
Dragon  Ice     646.0  700.0  125.0   130.0     90.0    130.0     90.0   95.0   
Psychic Dark    720.0  680.0   80.0   160.0     60.0    170.0    130.0   80.0   
Steel   Dragon  483.0  680.0  100.0   120.0    120.0    150.0    100.0   90.0   
Dragon  Fire    643.0  680.0  100.0   120.0    100.0    150.0    120.0   90.0   
...               ...    ...    ...     ...      ...      ...      ...    ...   
Poison  Bug     451.0  330.0   40.0    50.0     90.0     30.0     55.0   65.0   
        Water   690.0  320.0   50.0    60.0     60.0     60.0     60.0   30.0   
Normal  Fairy   174.0  270.0  103.0    45.0     40.0     45.0     40.0   20.0   
Bug     Water   283.0  269.0   40.0    30.0     32.0     50.0     52.0   65.0   
        Ghost   292.0  236.0    1.0    90.0     45.0     30.0     30.0   40.0   

                Generation  Legendary  
Type 1  Type 2                         
Ground  Fire           3.0        1.0  
Dragon  Ice            5.0        1.0  
Psychic Dark           6.0        1.0  
Steel   Dragon         4.0        1.0  
Dragon  Fire           5.0        1.0  
...                    ...        ...  
Poison  Bug            4.0        0.0  
        Water          6.0        0.0  
Normal  Fairy          2.0        0.0  
Bug     Water          3.0        0.0  
        Ghost          3.0        0.0  

[136 rows x 10 columns]